---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.39.31
vector:
  hosts:
    vector-01:
      ansible_host: 178.154.201.209
lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 84.252.129.46      